version: '3.8'

services:
  sorteo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src  # Adicionado para configurar actualización de la imagen con los cambios en la app.
